name: CI Pipeline
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar python3-venv
        run: sudo apt install python3.14-venv -y

      - name: Criar ambiente virtual
        run: python3 -m venv venv

      - name: Instalar Dependências
        run: |
          venv/bin/pip install --upgrade pip
          venv/bin/pip install -r requirements.txt

      - name: Executar testes com pytest
        run: |
          venv/bin/pytest test_calculadora.py -v --tb=short
